require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProcedurexesController do

  # This should return the minimal set of attributes required to create a valid
  # Procedurex. As you add validations to Procedurex, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProcedurexesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all procedurexes as @procedurexes" do
      procedurex = Procedurex.create! valid_attributes
      get :index, {}, valid_session
      assigns(:procedurexes).should eq([procedurex])
    end
  end

  describe "GET show" do
    it "assigns the requested procedurex as @procedurex" do
      procedurex = Procedurex.create! valid_attributes
      get :show, {:id => procedurex.to_param}, valid_session
      assigns(:procedurex).should eq(procedurex)
    end
  end

  describe "GET new" do
    it "assigns a new procedurex as @procedurex" do
      get :new, {}, valid_session
      assigns(:procedurex).should be_a_new(Procedurex)
    end
  end

  describe "GET edit" do
    it "assigns the requested procedurex as @procedurex" do
      procedurex = Procedurex.create! valid_attributes
      get :edit, {:id => procedurex.to_param}, valid_session
      assigns(:procedurex).should eq(procedurex)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Procedurex" do
        expect {
          post :create, {:procedurex => valid_attributes}, valid_session
        }.to change(Procedurex, :count).by(1)
      end

      it "assigns a newly created procedurex as @procedurex" do
        post :create, {:procedurex => valid_attributes}, valid_session
        assigns(:procedurex).should be_a(Procedurex)
        assigns(:procedurex).should be_persisted
      end

      it "redirects to the created procedurex" do
        post :create, {:procedurex => valid_attributes}, valid_session
        response.should redirect_to(Procedurex.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved procedurex as @procedurex" do
        # Trigger the behavior that occurs when invalid params are submitted
        Procedurex.any_instance.stub(:save).and_return(false)
        post :create, {:procedurex => {}}, valid_session
        assigns(:procedurex).should be_a_new(Procedurex)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Procedurex.any_instance.stub(:save).and_return(false)
        post :create, {:procedurex => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested procedurex" do
        procedurex = Procedurex.create! valid_attributes
        # Assuming there are no other procedurexes in the database, this
        # specifies that the Procedurex created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Procedurex.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => procedurex.to_param, :procedurex => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested procedurex as @procedurex" do
        procedurex = Procedurex.create! valid_attributes
        put :update, {:id => procedurex.to_param, :procedurex => valid_attributes}, valid_session
        assigns(:procedurex).should eq(procedurex)
      end

      it "redirects to the procedurex" do
        procedurex = Procedurex.create! valid_attributes
        put :update, {:id => procedurex.to_param, :procedurex => valid_attributes}, valid_session
        response.should redirect_to(procedurex)
      end
    end

    describe "with invalid params" do
      it "assigns the procedurex as @procedurex" do
        procedurex = Procedurex.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Procedurex.any_instance.stub(:save).and_return(false)
        put :update, {:id => procedurex.to_param, :procedurex => {}}, valid_session
        assigns(:procedurex).should eq(procedurex)
      end

      it "re-renders the 'edit' template" do
        procedurex = Procedurex.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Procedurex.any_instance.stub(:save).and_return(false)
        put :update, {:id => procedurex.to_param, :procedurex => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested procedurex" do
      procedurex = Procedurex.create! valid_attributes
      expect {
        delete :destroy, {:id => procedurex.to_param}, valid_session
      }.to change(Procedurex, :count).by(-1)
    end

    it "redirects to the procedurexes list" do
      procedurex = Procedurex.create! valid_attributes
      delete :destroy, {:id => procedurex.to_param}, valid_session
      response.should redirect_to(procedurexes_url)
    end
  end

end
